### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by JisiDais1** [ZakBlystone/gmod_blueprints#10]
Throws an error when creating any structure.
![image](https://user-images.githubusercontent.com/60583645/73614938-b73a3180-4625-11ea-8369-aca326f8e61a.png)

**Comment by ZakBlystone** [comment]
I can't seem to get this error to happen. Do you have any more details surrounding this?

**Comment by JisiDais1** [comment]
I'm just trying to create something from Structures

**Comment by JisiDais1** [comment]
Are you using the garry's mod beta? If so, which one?

**Comment by ZakBlystone** [comment]
Have you tried un-subscribing and re-subscribing to the addon?
Also, what other addons are you running?
Does this happen in singleplayer, multiplayer, or both?
Are you connected to a dedicated server?
Is this on Linux, Mac, or PC?

**Comment by JisiDais1** [comment]
1) Yes
2) All are disabled, maybe add-ons that are not installed through the workshop.
3) I test only in single
4) No
5) Windows

**Comment by JisiDais1** [comment]
That's it, I fixed it, maybe some addon was in conflict.
