### ISSUE TITLE
[Feature Request] Net.start

### ISSUE THREAD

**Issue by chickencvgmailcom** [ZakBlystone/gmod_blueprints#101]
Im trying to make Anti nextbot weapon with this addon,
BUT WHERE IS NET.START?????

**Comment by chickencvgmailcom** [comment]
![image](https://user-images.githubusercontent.com/78594098/193378460-9b308a51-a480-402c-97d1-8b426c170fe0.png)

**Comment by chickencvgmailcom** [comment]
HOW

**Comment by ZakBlystone** [comment]
![image](https://user-images.githubusercontent.com/18226128/193424435-d2b778a6-834c-4b11-aad9-9492946a9026.png)

Create an Event (click the + on Events)
Select it by clicking on it twice (this will bring up and editor in the sidebar)
Add the pins you want
Select the netmode you want:
- Broadcast (sends from server to all clients)
- Send to Client (sends from server to a specific client)
- Send to Server (sends from client to server)

Drag the Entry onto the graph and select 'Hook <event>' to place a hook node.
Drag again and select 'Call <event>' to place the call node.
