### ISSUE TITLE
[V2] Node Library names with hyphens don't work.

### ISSUE THREAD

**Issue by yukiqt** [ZakBlystone/gmod_blueprints#102]
Context: I'm running a map ([rp_site65](https://steamcommunity.com/workshop/filedetails/?id=1788306202)) that has custom Lua hooks.
All the map hooks (except nukes) have hyphens in the name.

![](https://i.possum.city/XOPwAIucuLYO5FI1.png)
![](https://i.possum.city/WQIaM2JMHIIpNXty.png)

**Comment by yukiqt** [comment]
Also applies to `.` (presumably other special characters as well)

**Comment by ZakBlystone** [comment]
Should be fixed in commit 5da09da20455d0229c994803235897896e11bb2d on V2
