### ISSUE TITLE
[Workshop] Unexpected symbol near '=' [again]

### ISSUE THREAD

**Issue by Famous5000** [ZakBlystone/gmod_blueprints#104]
Shareable key: bp-IodpMs7LpKb1GZj73dBP

Line issue occurs on: 491

I can't seem to get rid of the error regardless of what I do. Please tell me if it's because my BP is fucked and please fix the issue so that it _at least_ tells people what went wrong.

**Comment by Famous5000** [comment]
A reinstall did not help with the issue. The script is trying to create an `Entity` which can take in multiple different types of paper to increase the value of the printed money. The string values are required for allowed entities [which I'm probably just going to merge into the single script it belongs to], and a temp value to handle the `IF:ELSE` statement which again is requested above.

I'm going to try to remove the string variable requirements and I'll report back if anything else is broken when it shouldn't be.

**Comment by Famous5000** [comment]
Update:
![image](https://github.com/user-attachments/assets/9cc1f55f-751b-4e62-a624-905211b20460)

**Comment by ZakBlystone** [comment]
This should now be fixed in fffb9271dddcdddfba10076b616202f770bb48de
