### ISSUE TITLE
Entity:SetMaterial 'materialName' pin should be 'materialPath'

### ISSUE THREAD

**Issue by jrinkman** [ZakBlystone/gmod_blueprints#11]
**Saved blueprint:** N/A
**Steps to reproduce the issue:** N/A
**Relevant console errors:** N/A

![image of node](https://i.imgur.com/b0mJYDw.png)

**Comment by ZakBlystone** [comment]
Fixed in commit fdf1033e0256fb99c822c2853b3d3c09958046f8
