### ISSUE TITLE
Literals don't handle negatives well

### ISSUE THREAD

**Issue by jrinkman** [ZakBlystone/gmod_blueprints#15]
**Example script:** [Pastebin link](https://pastebin.com/raw/te1066zR)
**Steps to reproduce:** Place down any literal.
**Any relevant console errors:** N/A

Negatives aren't displayed in the literal text, and the negative value doesn't hold when changing a literal value.

**Comment by ZakBlystone** [comment]
Fixed in commit efe8bf1c31afdf8be3010ea3f12977ef6e6998d9
