### ISSUE TITLE
While entrypoint is okay-ish, store the rest of the code outside autorun folder

### ISSUE THREAD

**Issue by ExtReMLapin** [ZakBlystone/gmod_blueprints#19]
It's fine to use two autorun files, but it's still recommended to not use abreviations to prevent [possible](https://en.wikipedia.org/wiki/Murphy%27s_law) common files names (colisions) with others addons.

Just move everything from `lua/autorun/*/*` to `lua/blueprints/*/*`

**Comment by ZakBlystone** [comment]
Updated in commit 5cd6d2a8ee1751d5b503fea7f74cada927507ae0
