### ISSUE TITLE
FrameNumber causes Blueprint to Freeze

### ISSUE THREAD

**Issue by Dagbafrosty** [ZakBlystone/gmod_blueprints#35]
I managed to freeze it when converting framenumber to non pure. 

bp-hDtA3QtCU3zTLt2LoN0R

**Comment by Hxrmn** [comment]
Fixed in commit 2210d1b17a5c9bd5e801a4075caad0447ab2586a

**Comment by ZakBlystone** [comment]
Fixed in commit 2210d1b17a5c9bd5e801a4075caad0447ab2586a
