### ISSUE TITLE
'Copy Wiki Link to Clipboard' feature for Node Context Menu

### ISSUE THREAD

**Issue by distributivgesetz** [ZakBlystone/gmod_blueprints#40]
When in the editor, you might want to visit the wiki page to get more info about a node, but it's pretty annoying and unnecessary to have to google the gmod wiki page and to look for the function there.

**Comment by ZakBlystone** [comment]
Implemented using `gui.OpenURL` in commit db0129802c17369d8b849386c9221d6b8f187b70
