### ISSUE TITLE
CTRL-Z changes display of == operator incorrectly

### ISSUE THREAD

**Issue by jrinkman** [ZakBlystone/gmod_blueprints#41]
**Steps to reproduce:**
1. Create blueprint: `bp-vi4mcJtz0iCO630UJWd0`
2. Do something
3. Undo
4. Node is now incorrectly displayed:

![Incorrect node](https://i.imgur.com/jHKRLdn.png)

**Comment by ZakBlystone** [comment]
Fixed in commit c069741a8b2f96167d5d1aa26b872127473feb6b
