### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by bruh109** [ZakBlystone/gmod_blueprints#49]
hi i have a problem with the addon
![Captura](https://user-images.githubusercontent.com/63554551/79074904-bf14f280-7cb4-11ea-9805-9646bd238258.PNG)

**Comment by ZakBlystone** [comment]
I have a few questions:
1. Are you running on a beta branch of gmod, or the default version?
2. What addons do you have installed?
3. Could you try disabling your other addons and see if that resolves the issue?

I can't seem to reproduce this issue locally.
Based on the error it seems that the `IsEnabled` function doesn't exist on `DButton` which should not happen.

**Comment by bruh109** [comment]
1.my gmod is: 14.07.11(public) is not the original is pirate
2.thats no the problem because i uninstall all my addons and only put that addon and no works 
:(

**Comment by bruh109** [comment]
sorry for reply late

**Comment by ZakBlystone** [comment]
Resolution: Buy a legitimate copy of Garry's mod that didn't come out 6 years ago. (It's only $10)
