### ISSUE TITLE
Feature Request: Communication between Server and Client

### ISSUE THREAD

**Issue by CubeMath** [ZakBlystone/gmod_blueprints#53]
There should be a way to send messages between Server and Client.
These messages should include: Strings, Boolean, Numbers and Entities.

Something similar like this:
```
SERVER:
function server_send()
  net.Start("MyMessage");
  net.WriteString("Hello World!");
  net.Send(player.GetAll());
end

CLIENT:
local function client_receive()
  local cl_str = net.ReadString();
  PrintMessage(HUD_PRINTTALK, cl_str);
end
net.Receive("MyMessage", client_receive);
```

**Comment by ZakBlystone** [comment]
This feature exists in the form of custom events:
https://blueprints.zakblystone.net/en/basics/events
