### ISSUE TITLE
changing pin names doesn't update across the project 

### ISSUE THREAD

**Issue by Crysoskis** [ZakBlystone/gmod_blueprints#55]
Renaming a Pin on a function will not update other blueprints that reference the pin
![image](https://user-images.githubusercontent.com/43220979/81524161-0074de00-9305-11ea-9b55-f455f3a01e6e.png)
These two functions are the same, but one has the old "Victim" variable name while the new one has the "Player" one

**Comment by ZakBlystone** [comment]
Fixed in commit 15e8259e3fecd7d5036be4d8b4bacba6b5951518
