### ISSUE TITLE
having an empty call event with no exec input causes a compiler error

### ISSUE THREAD

**Issue by Crysoskis** [ZakBlystone/gmod_blueprints#57]
Leaving a Call Event with no exec connection in a blueprint causes this compiler error:
![image](https://user-images.githubusercontent.com/43220979/81628529-c0b9ff00-93b5-11ea-9a89-26d5c07ebb41.png)

What it looks like:
![image](https://user-images.githubusercontent.com/43220979/81628585-e7783580-93b5-11ea-8591-1d9d92dabdbe.png)

Happens on main EventGraph and any other graph

**Comment by ZakBlystone** [comment]
Fixed in commit d2a35d73187fdd55daebbbe7035c35c632081591
