### ISSUE TITLE
Having multiple Mod objects in one project causes issues

### ISSUE THREAD

**Issue by Crysoskis** [ZakBlystone/gmod_blueprints#58]
A project with more then one Mod object will randomly pick a mod to execute and ignore others, sometimes executing a Mod object more then once.

Example of project that has this behavior (bp id is: bp-G31VWsfu6vsucb6Gtq5f ):
![image](https://user-images.githubusercontent.com/43220979/81644789-43a28000-93dd-11ea-9a09-e15c170a1729.png)

Each Mod object has an init component connected to a chatPrintAll component saying the mod was initialized.
![image](https://user-images.githubusercontent.com/43220979/81644950-895f4880-93dd-11ea-8fc1-bd0678535e28.png)
![image](https://user-images.githubusercontent.com/43220979/81644991-99772800-93dd-11ea-84e1-d762770c840d.png)
![image](https://user-images.githubusercontent.com/43220979/81645020-aa279e00-93dd-11ea-849a-8cbff32ec7de.png)

The AmmoDropper mod is initialized twice, but the WeaponDropper and DebugMod are not and do not run any code.
![image](https://user-images.githubusercontent.com/43220979/81645135-e1964a80-93dd-11ea-8989-13f325bf9e66.png)

**Comment by ZakBlystone** [comment]
Fixed in commit 630c61703ec682a073119398a0194fb6f30a3332
