### ISSUE TITLE
alt+click on a node no longer clears the node

### ISSUE THREAD

**Issue by Crysoskis** [ZakBlystone/gmod_blueprints#60]
In editor alt+click used to clear the node, dragging creating a new wire for connection. alt+click no longer clears the node, just creates a new wire connection.

**Comment by ZakBlystone** [comment]
are you sure it's not ctrl+click?

**Comment by Crysoskis** [comment]
In the workshop version alt+click deleted the connection on the node, ctrl+click just picks up the wire from the node

**Comment by ZakBlystone** [comment]
Implemented in commit 23df6f904eacbaa9df9b3e01cfad6a44c4fb665d
