### ISSUE TITLE
referencing a function from a mod object causes a compiler error

### ISSUE THREAD

**Issue by Crysoskis** [ZakBlystone/gmod_blueprints#61]
If you reference a function from a Mod object you are unable to set the "Self" node on the function which causes a compiler error.

Blueprint showing this behavior: bp-FgtGHid8GViX2egMHkqW

The function:
![image](https://user-images.githubusercontent.com/43220979/81712686-c3563c00-9429-11ea-9c55-47c30cac963f.png)

The function inside its own object (this does not create a compiler error):
![image](https://user-images.githubusercontent.com/43220979/81712763-db2dc000-9429-11ea-83fe-a0387b2b085c.png)

The function inside an object in the same project (this creates the error):
![image](https://user-images.githubusercontent.com/43220979/81712929-1203d600-942a-11ea-8b94-3bdfadbbd36f.png)

Create isnt an option on the DebugMod mod so you cant grab a value for "Self"
![image](https://user-images.githubusercontent.com/43220979/81713069-45defb80-942a-11ea-8294-4b937c197bd5.png)

The compiler error:
![image](https://user-images.githubusercontent.com/43220979/81713180-660eba80-942a-11ea-8546-d4ddfb687deb.png)

**Comment by ZakBlystone** [comment]
Fixed in commit 8c3267d7564e728558f629b1d6c4b7f0638bef58
