### ISSUE TITLE
objects in a project initialize twice

### ISSUE THREAD

**Issue by Crysoskis** [ZakBlystone/gmod_blueprints#62]
When a project runs for the first time each Mod object initializes twice, overriding the first initialization.

Blueprint showing this behavior: bp-flfwqOdNhCnCzfC3SV1n

![image](https://user-images.githubusercontent.com/43220979/81713811-32806000-942b-11ea-9d9c-378f928c576e.png)

**Comment by ZakBlystone** [comment]
Fixed in commit 9ffd10e2742a3c4b9243b53241a8b216c2fb912e
