### ISSUE TITLE
deleting an object in a project that has functions referenced in other objects can brick the project

### ISSUE THREAD

**Issue by Crysoskis** [ZakBlystone/gmod_blueprints#63]
Sometimes deleting an object that has functions referenced in other objects can brick the entire project or just cause issues in general 

Uploading to server causes console flooding:
![image](https://user-images.githubusercontent.com/43220979/82079548-dff7ab80-9697-11ea-92bb-1558cbfc6918.png)

And can trigger visual glitches:
![image](https://user-images.githubusercontent.com/43220979/82079593-f271e500-9697-11ea-926c-e69f9ac81c79.png)

![image](https://user-images.githubusercontent.com/43220979/82080144-e175a380-9698-11ea-8189-ca6c1de643cd.png)

Has a chance to break blueprints:
![image](https://user-images.githubusercontent.com/43220979/82079651-0cabc300-9698-11ea-9c19-23157a236cf6.png)
AmmoDropper tabs cannot be closed, and appear as empty when viewed. script errors happen when one is opened.

How to reproduce:
1. Create new project
2. Create a new object, name it Test1
3. Create another object, name it Test2
4. Create a function that does something in Test1
5. Call Test1's function in Test2
6. Save and upload
7. Delete the Test1 Object
8. Save and upload
9. Bug occurs. Can brick a project until the server restarts. Has a chance to permanently brick a project.

Bricked project: bp-wDBaUyZzR98lspxGEunX
Object DebugMod bricked this blueprint after it was deleted.

**Comment by ZakBlystone** [comment]
Fixed in commit 45dd42ec534c3351f12a22438e5a58346c7d2e6e
Will integrate into v2-stable after some testing.

**Comment by NMM3N** [comment]
### 

> [****](`url`)
