### ISSUE TITLE
[Bug] Red flashing invalid, when using hook in node library that accepts a return

### ISSUE THREAD

**Issue by Matt4499** [ZakBlystone/gmod_blueprints#81]
Blueprints Branch V2

It creates two player classes instead of "extending" off of the base Player class.

When attempting to create a hook that accepts a return value, the node starts flashing red and says Invalid. This is spammed in the console: 
```
No Match for: [nodeless]Inputs (IN) [bppintype(table: 0x027ff1226658): Boolean]
  Node Preview:DarkRP_Hooks_canArrest.Exec (OUT) [bppintype(table: 0x027fec7c70b8): Exec]
  Node Preview:DarkRP_Hooks_canArrest.Arrester (OUT) [bppintype(table: 0x027fec3ddf48): Player]
  Node Preview:DarkRP_Hooks_canArrest.Arrestee (OUT) [bppintype(table: 0x027fec13a4e8): Player]
```

As soon as the returns are removed, it stops flashing invalid.

**Comment by ZakBlystone** [comment]
Fixed in commit ff703342fd69cef8c38cd7ac7f4bdd487bcc3c93
