### ISSUE TITLE
Messed up cursor location in ui

### ISSUE THREAD

**Issue by UltraBlackLinux** [ZakBlystone/gmod_blueprints#87]
Hey there,
It seems like the blueprint ui has some problems with correctly tracking the cursor location. A very easy way to see this is to just hold leftclick on an empty space and one can instandly see a pretty large selection box. Also node connecting is weird because of this.
It's only cosmetical, but please fix this!
Thank you!

**Comment by ZakBlystone** [comment]
Hello,
Can you post some screenshots of the problem and tell me your screen resolution + windowed / no-border settings?
I don't think I've seen this issue before.
Thanks.

**Comment by UltraBlackLinux** [comment]
![Screenshot_331](https://user-images.githubusercontent.com/62404294/148236228-e869a770-bb9e-4a81-b47a-bdf98271ea79.png)
![Screenshot_332](https://user-images.githubusercontent.com/62404294/148236233-d7900cd1-1bdc-4f09-ba31-0bd63ff05d1e.png)
Both screenshots were taken without moving the mouse. Just clicking and holding

**Comment by ZakBlystone** [comment]
Hi, I need more information to reproduce this bug.

What is your screen resolution?
Are you in fullscreen mode, windowed, or borderless?
Is the blueprint window maximized?

**Comment by UltraBlackLinux** [comment]
1920x1200
*
*

**Comment by UltraBlackLinux** [comment]
Huh. Seems like it fixed itself - Might be related to me switching to the chromium branch
