### ISSUE TITLE
String autocomplete error when pressing tab

### ISSUE THREAD

**Issue by samuelmaddock** [ZakBlystone/gmod_blueprints#9]
**Steps to reproduce**
1. Open string input for function parameter.
1. Start typing in `sound/` to open autocomplete options.
1. Press tab.

**Observed**
String input closes while autocomplete options remain open. A Lua error is emitted:
```
[ERROR] lua/vgui/dtextentry.lua:222: Tried to use invalid object (type Panel) (Object was NULL or not of the right type)
  1. SetText - [C]:-1
   2. DoClick - lua/vgui/dtextentry.lua:222
    3. OnMouseReleased - lua/vgui/dlabel.lua:234
     4. unknown - lua/vgui/dmenuoption.lua:77
```

**Expected**
Autocomplete option is selected as the string parameter.

**Comment by ZakBlystone** [comment]
Fixed in commit 873e47d9642cfe82b0fc7b5008fdc633ffc00aa5
