### ISSUE TITLE
Weapons stuff missing

### ISSUE THREAD

**Issue by UltraBlackLinux** [ZakBlystone/gmod_blueprints#90]
Hey there,
I noticed that [this](https://wiki.facepunch.com/gmod/weapons) is missing from the node menu - Why is that?
Am  I misunderstanding some of the fundamental concepts of this addon?
Thanks!

**Comment by ZakBlystone** [comment]
There are a few functions in gmod Lua that don't map neatly into Blueprint's strictly-typed ecosystem.
The weapons.* functions mostly return generic tables of functions and variables.
But Blueprint has no way of determining the types of the table fields.

If there is some specific way you want to use these functions, I'm sure I can figure something out for ya.

**Comment by ZakBlystone** [comment]
I figured out a solution. I've created a struct for the SWEP data.
You should be able to use weapons.Get and weapons.GetList now.

Let me know if you need something more than that.

**Comment by UltraBlackLinux** [comment]
This is actually perfect and all that I've been trying to get! Thank you so much!
