### ISSUE TITLE
[v2] Trouble with Saving/Blueprints lua error

### ISSUE THREAD

**Issue by UltraBlackLinux** [ZakBlystone/gmod_blueprints#91]
Hey there,
I just found this feature called "Projects and decided that I would port some standalone blueprints into a singular project, but the "unsaved stuff" star doesn't want to disappear and when I tried uploading my blueprint to the server I got a lua error: ![Screenshot_346](https://user-images.githubusercontent.com/62404294/148654892-0d1f0170-33b2-4eac-976a-88f8a0464035.png)
I don't know what this is, but please fix this I guess. I hope it's actually gonna save...
Thanks!

**Comment by ZakBlystone** [comment]
This is an issue with manually copying nodes between modules.
I will look into either supporting / preventing this.
