### ISSUE TITLE
[v2] Another weird error

### ISSUE THREAD

**Issue by UltraBlackLinux** [ZakBlystone/gmod_blueprints#92]
I got this after trying to create an entity and me experimenting with JsonToTable:
![Screenshot_347](https://user-images.githubusercontent.com/62404294/148657112-15ad2e92-cfdd-48cd-be37-017bf09210ac.png)

**Comment by ZakBlystone** [comment]
How do I recreate this bug, what steps?

**Comment by UltraBlackLinux** [comment]
I really don't know how this happened. I was just experimenting with json and suddenly I couldn't move any more nodes and always got this when trying to do so. This happened right after the issue with my manual importing of stuff into a project failed so the addon might have bugged out like this.

**Comment by ZakBlystone** [comment]
Should be fixed in revision 371e9842f8ae8e0de7185b4b2475a7f8d56ae8a4
