### ISSUE TITLE
[v2] Error uploading Project to server

### ISSUE THREAD

**Issue by UltraBlackLinux** [ZakBlystone/gmod_blueprints#93]
![Screenshot_354](https://user-images.githubusercontent.com/62404294/148683137-a4e43bf2-2c66-4ae6-98c5-9aeb9aa49a57.png) - Uploading them one by one works - Is project handling not yet fully done?
Why am I finding all of these :/

**Comment by ZakBlystone** [comment]
When you post these bugs can you please please please please:
1. tell me how to get the problem to happen 
 or
2. send me the broken stuff
 
It would make my life so much easier than trying to debug this from a screenshot of a stack trace.

**Comment by UltraBlackLinux** [comment]
Oh sorry, I thought it was clear - I got that error when I pressed "UL to Server" while having the project  
 file overview opened. When I tried it while having the editor open it worked.

Sorry that my descs are getting unclear. I tend to get lazy after a while... xD

**Comment by UltraBlackLinux** [comment]
The more I think about it, I may have tried to upload my manually ported borked blueprint to the server and that caused this error - Is that plausible?

**Comment by UltraBlackLinux** [comment]
I think I'm gonna close this until I can reproduce it
