### ISSUE TITLE
[v2] Unexpected symbol near '['

### ISSUE THREAD

**Issue by UltraBlackLinux** [ZakBlystone/gmod_blueprints#96]
Hey again,
this time hopefully with better issue practice.
I'm getting this error: ![Screenshot_355](https://user-images.githubusercontent.com/62404294/149590085-581bb9e2-0fea-4fa8-9476-b416774bde3f.png)
This is my blueprint: bp-a2kMOXdxdLn0hArVCFLk
Is this another one of those your-bp-is-fucked-problems?
Thanks!

**Comment by ZakBlystone** [comment]
Fixed in commit a70dbc9.
You have a disconnected pin on your ForEachIReverse in Loot Spawner Entity : SpawnablesSetup

**Comment by UltraBlackLinux** [comment]
oh thanks, I didn't even notice
