### ISSUE TITLE
[v2] ')' expected near 'have' - Missing escapes

### ISSUE THREAD

**Issue by UltraBlackLinux** [ZakBlystone/gmod_blueprints#97]
Hey there,
I encountered that error trying to create a convar with a description containing quotation maks and uploading the blueprint - This error supposedly is from the function "Game Manager/StartGame".
I am using v2 as stated in the title and this is the blueprint: bp-pxmeDTO53HRyYSrhD49h
Thanks!

EDIT: It turns out that there is some escaping missing: ![](https://i.imgur.com/bDOha67.png)

**Comment by ZakBlystone** [comment]
Fixed in commit 5e58fd3
